In [2]:
import numpy as np 
from math import *
import random as r

In [13]:
# heatmap function

def random_position(dim):
    return r.random() * dim[0], r.random()*dim[1]
def genData(time_steps:int, particles, dim, func: callable):
    data = []
    for t in range(time_steps):
        data.append([])
        for x in range(particles):
            data[t].append(func(dim))
    return data
    
    
            
    

def fheatmap(data,resolution:tuple, dimensions: tuple, origin: tuple):
    heatmap = np.zeros((resolution[1],resolution[0]))
    dimmap = []
    xconv = dimensions[0]/resolution[0]
    yconv = dimensions[1]/resolution[1]
    
    # first constuct edge borders
    
    dimmap.append([])
    for x in range(len(heatmap[0]) + 1):
        xcoord = xconv * x + origin[0]
        dimmap[-1].append(xcoord)
        
    dimmap.append([])
    for y in range(len(heatmap) + 1):
        ycoord = yconv * y + origin[1]
        dimmap[-1].append(ycoord)
    
    div_size: int = len(data[0])
    for t in data:
        for p in t:
            x = p[0]
            y = p[1]
            xind = -1
            yind = -1
            
            # search x
            index: int = len(dimmap[0]) // 2
            step = index // 2
            for loop in range(div_size):
                
                if x < dimmap[0][index + 1] and x > dimmap[0][index]:
                    xind = index
                    
                    break
                elif x < dimmap[0][index]:
                    index = index - step
                
                elif x > dimmap[0][index]:
                    index = index + step
                    
                
                step = step // 2
                    
                    
            # search y
            index: int = len(dimmap[1]) // 2
            step = index // 2
            
            for loop in range(div_size):
                if y < dimmap[1][index + 1] and y > dimmap[1][index]:
                    yind = index
                    
                    break
                elif y < dimmap[1][index]:
                    index = index - step
                
                elif y > dimmap[1][index]:
                    index = index + step
                    
                
                step = step // 2
                    
            
            heatmap[yind][xind] += 1
            
            
            
            
           
            
    
    print(np.array(heatmap))
    print(np.array(data))
    
    


In [14]:
d = genData(10,10,(2,3),random_position)
fheatmap(d,(10,10),(2,3),(0,0))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 2. 2. 1. 6.]
 [0. 0. 0. 0. 2. 1. 1. 2. 1. 0.]
 [0. 0. 0. 0. 1. 2. 2. 0. 0. 2.]
 [0. 0. 2. 0. 2. 1. 2. 1. 2. 2.]
 [0. 0. 3. 1. 1. 0. 0. 2. 3. 0.]
 [0. 0. 1. 1. 1. 3. 2. 0. 0. 3.]
 [0. 0. 0. 1. 0. 1. 3. 2. 1. 2.]
 [0. 0. 2. 5. 2. 1. 3. 2. 6. 9.]]
[[[1.17859108 2.39049907]
  [0.53524505 1.82930094]
  [1.68931215 0.4249557 ]
  [1.64857931 0.03459746]
  [1.60827416 2.86155902]
  [0.65137335 0.35451822]
  [0.71569114 2.29718811]
  [1.77894746 2.52171635]
  [1.77141096 1.9024748 ]
  [1.05419053 0.69208422]]

 [[0.37743323 2.4085115 ]
  [1.36391544 2.11568979]
  [1.17740739 1.15999377]
  [0.82378093 0.29195519]
  [0.23941527 2.24307322]
  [1.98729017 2.45680272]
  [0.80563491 1.82488754]
  [1.67963462 2.03975405]
  [0.09855468 1.69565057]
  [0.41157844 1.73802763]]

 [[0.76343938 0.02431347]
  [1.29387459 1.70458536]
  [1.21255821 0.80997779]
  [0.46931676 0.35658205]
  [1.53618905 1.99614718]
  [0.74477264 0

In [1]:
def X (a,kbt,A,T,theta):
    theta = atan(theta)
    print((A/0.2)*tanh(1/(a*10*2*pi)))
    print(A)
    
    
    F = sqrt( pow(T,2.0) + pow(T * tan(theta),2.0))
    B = 1/(a*10*2*pi)
    am = A * 1/(a*10*2*pi)
    
    V = (am)/0.2
    
    
    output = F*pow(a,2) * pow(1/kbt,2) * V / pow(pi,2)
    return output

def Y (a,kbt,T,theta,utheta):
    theta = atan(theta)
    utheta = atan(utheta)
    F = sqrt( T**2 + pow(T * tan(theta),2))
    output =F*a*theta * (1/kbt) * 1/pi
    uoutput = F*a*utheta * (1/kbt) * 1/pi
    return (output, uoutput)